import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "serene-buddha-head",
    name: "Serene Buddha Head White Marble Sculpture",
    deity: "Buddha — The Enlightened One",
    price: 14000,
    originalPrice: 14000,
    material: "White Marble Statue",
    height: "10 inches",
    weight: "6 kg",
    description: "Cultivate peace with a 10-inch white marble Buddha head. A premium, hand-carved Jaipur masterpiece. Elevate your space with free shipping.",
    longDescription: "This breathtaking 10-inch Serene Buddha Head in White Marble is a sublime masterpiece of spiritual artistry. Hand-carved by master artisans from premium solid white marble, it embodies the ultimate state of inner peace, mindfulness, and enlightenment. Every detail, from the beautifully spiraled ushnisha (the cranial bump representing spiritual wisdom) to the soft, half-closed eyes and gentle, tranquil smile, has been meticulously chiseled to perfection. The pristine white marble features a polished, velvet-smooth finish that reflects light with a soft, ethereal glow, creating a calming sanctuary in any space. Perfect for modern home entrances, living rooms, meditation corners, or premium corporate wellness gifts, this sculpture serves as a gentle daily reminder of clarity, focus, and serenity.",
    images: [
      "/products/buddha-head-hero.png"
    ],
    rating: 4.9,
    reviews: 24,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Polished Pure White Marble",
    origin: "MADE IN INDIA",
    keywords: "buddha head marble sculpture, white marble buddha statue, buy buddha head online, meditative buddha bust, marble buddha head 10 inch, home decor buddha, premium mindfulness gift",
    purpose: "Mindfulness, Peace, Home Decor, Meditation Corner, Premium Gift",
    features: [
      "Premium White Marble",
      "Height: 10 inches (25 cm)",
      "Width: 6.5 inches (16.5 cm)",
      "Depth: 6 inches (15 cm)",
      "Weight: 6 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "saraswati-music",
    name: "15\" The Saraswati - Goddess Of Music | Pristine White Marble",
    deity: "Saraswati — The Goddess of Knowledge & Arts",
    price: 100065,
    originalPrice: 100065,
    material: "Pristine White Marble",
    height: "15 inches",
    weight: "11 kg",
    description: "Invite wisdom with this 15-inch white marble Saraswati idol. Masterfully hand-carved by Jaipur artisans. Shop now with free shipping.",
    longDescription: "This exquisite 15-inch (38 cm) statue of Goddess Saraswati is a masterpiece of sacred art, hand-carved from premium Pristine White Marble—the same pristine stone used in the Taj Mahal. Every detail of this divine 11 kg figurine captures the pure essence of the Goddess of Knowledge, Music, and Arts. \n\nSaraswati is depicted in a graceful seated posture, her four arms representing the four aspects of human personality in learning: mind, intellect, alertness, and ego. She delicately holds the Veena, the symbol of the harmony of all creative arts and sciences. Her other hands hold the Vedas (symbolizing true knowledge) and a crystal mala (representing the power of meditation and spirituality). \n\nThe artisan has used traditional Jaipur chiseling techniques passed down through generations to create the intricate floral patterns on her garments and the delicate features of her face, which radiates a serene, meditative peace. Accented with subtle 24K gold leaf detailing on her crown and ornaments, this murti is not just a sculpture but a living presence of inspiration. Ideal for homes, professional studios, and creative spaces, it brings a vibration of clarity and wisdom to any study room, music studio, or home mandir. Each piece is unique, bearing the subtle marks of the artisan's hand and the natural veining of the White marble, ensuring you possess a one-of-a-kind sacred treasure.",
    images: [
      "/products/saraswati-hero.png",
      "/products/saraswati-1.png",
      "/products/saraswati-2.jpg",
      "/products/saraswati-3.png",
      "/products/saraswati-4.png",
      "/products/saraswati-5.jpg"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Pristine White Marble with Gold",
    origin: "MADE IN INDIA",
    keywords: "saraswati murti price, saraswati marble statue, goddess of music idol, buy saraswati murti online, white marble saraswati, premium saraswati idol for home altar, housewarming gift for new home",
    purpose: "Education, Arts, Music, Wisdom, Home Mandir",
    features: [
      "Pristine White Marble",
      "Height: 38 cm (15 inch)",
      "Width: 25.5 cm (10 inch)",
      "Depth: 12.5 cm (5 inch)",
      "Weight: 11 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "nandi-auspicious",
    name: "Nandi: An Auspicious Presence",
    deity: "Nandi — The Sacred Bull",
    price: 140700,
    originalPrice: 140700,
    material: "White Marble Statue",
    height: "16.5 inches",
    weight: "56.55 kg",
    description: "Secure this sacred 16.5-inch white marble Nandi. Flawlessly handcrafted in Jaipur to guard your mandir. Order now with free shipping.",
    longDescription: "A glorious 16.5-inch (42 cm) statue of Nandi, the sacred bull and devoted vahana of Lord Shiva. Meticulously carved from pristine white marble, this 56.55 kg murti radiates peace, devotion, and auspiciousness, making it a perfect addition to any divine altar.",
    images: [
      "/products/nandi-hero.png",
      "/products/nandi-1.png",
      "/products/nandi-2.png",
      "/products/nandi-3.png",
      "/products/nandi-4.png",
      "/products/nandi-5.png"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Polished White Marble",
    origin: "MADE IN INDIA",
    keywords: "nandi murti price, nandi marble statue, shiva bull idol, buy nandi murti online, white marble nandi jaipur, sacred bull for shiva temple, nandi statue quality",
    purpose: "Devotion, Peace, Shiva Temple, Home Mandir",
    features: [
      "White Marble Statue",
      "Height: 42 cm (16.5 inch)",
      "Width: 56 cm (22 inch)",
      "Depth: 28 cm (11 inch)",
      "Weight: 56.55 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "durga-maa-large",
    name: "39\" Large Durga Maa Statue - The Warrior Form Of Parvati",
    deity: "Durga — The Invincible Force",
    price: 520380,
    originalPrice: 520380,
    material: "Pristine White Marble",
    height: "39 inches",
    weight: "140 kg",
    description: "Honor the Divine Mother with a majestic 39-inch white marble Durga murti. Expertly handcrafted in Jaipur. Shop with free global shipping.",
    longDescription: "A massive and awe-inspiring 39-inch (99 cm) marble statue of Goddess Durga riding her fierce lion. Crafted from premium Pristine White Marble, this 140 kg masterpiece intricately depicts the Warrior Form of Parvati with Her eight arms, each holding a divine weapon to protect the universe.",
    images: [
      "/products/durga-maa-hero.png",
      "/products/durga-maa-1.jpg",
      "/products/durga-maa-2.jpg",
      "/products/durga-maa-3.jpg",
      "/products/durga-maa-4.jpg",
      "/products/durga-maa-5.png"
    ],
    rating: 5.0,
    reviews: 2,
    inStock: true,
    badge: "Premium",
    category: "Marble",
    finish: "Pristine White Marble with Gold",
    origin: "MADE IN INDIA",
    keywords: "durga maa murti price, large durga statue jaipur, marble durga idol shop, buy durga murti online india, parvati murti premium, durga statue manufacturer, mahishasuramardini marble",
    purpose: "Protection, Strength, Victory, Home Temple",
    features: [
      "Pristine White Marble",
      "Height: 99 cm (39 inch)",
      "Width: 76 cm (30 inch)",
      "Depth: 20.5 cm (8 inch)",
      "Weight: 140 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "vishnu-lakshmi-set",
    name: "18\" Standing Vishnu - Lakshmi in Blessing Gesture | Set of Two",
    deity: "Vishnu & Lakshmi",
    price: 160125,
    originalPrice: 160125,
    material: "White Marble Statues",
    height: "18 inches",
    weight: "Handmade",
    description: "Invite prosperity with an 18-inch white marble Vishnu and Lakshmi set. Authentic Jaipur craftsmanship. Order for free worldwide shipping.",
    longDescription: "A breathtaking pair of white marble statues depicting Lord Vishnu and Goddess Lakshmi in a supreme blessing gesture. Standing at 18 inches and 17 inches respectively, these handcrafted murtis feature exquisite gold detailing and intricate stonework, representing the ultimate divine union of preservation and prosperity.",
    images: [
      "/products/vishnu-lakshmi-set-hero.png",
      "/products/vishnu-lakshmi-set-1.jpg",
      "/products/vishnu-lakshmi-set-2.png",
      "/products/vishnu-lakshmi-set-3.jpg",
      "/products/vishnu-lakshmi-set-4.jpg",
      "/products/vishnu-lakshmi-set-5.jpg"
    ],
    rating: 5.0,
    reviews: 6,
    inStock: true,
    badge: "Masterpiece Set",
    category: "Marble",
    finish: "Hand-painted White Marble with Gold",
    origin: "MADE IN INDIA",
    keywords: "vishnu lakshmi murti set price, vishnu lakshmi marble idol jaipur, buy divine pair online india, luxury lakshmi vishnu statue, marble deity set shop, jaipur handcrafted murtis",
    purpose: "Wealth, Preservation, Peace, Home Mandir",
    features: [
      "White Marble Statues",
      "Vishnu: 18\" H x 7.5\" W x 4\" D",
      "Lakshmi: 17\" H x 7\" W x 4\" D",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "krishna-lotus-throne",
    name: "14\" Murli Manohara Krishna Marble Statue on a Lotus Throne",
    deity: "Krishna — The Divine Flutist",
    price: 63000,
    originalPrice: 63000,
    material: "Marble Statue",
    height: "14.8 inches",
    weight: "13.11 kg",
    description: "Adorn your mandir with a 14.8-inch marble Krishna on a lotus throne. Premium handcrafted Jaipur artistry. Shop now with free delivery.",
    longDescription: "A breathtaking 14.8-inch (37.5 cm) marble statue of Murli Manohara Krishna gracefully seated on a vibrant lotus throne. Every detail, from the divine peacock feather crown to the delicately held flute, is masterfully hand-painted to capture the enchanting beauty and eternal joy of the Lord.",
    images: [
      "/products/krishna-lotus-hero.png",
      "/products/krishna-lotus-1.png",
      "/products/krishna-lotus-2.png",
      "/products/krishna-lotus-3.jpg",
      "/products/krishna-lotus-4.jpg"
    ],
    rating: 5.0,
    reviews: 4,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted Marble",
    origin: "MADE IN INDIA",
    keywords: "krishna murti on lotus price, murli manohara statue jaipur, lord krishna idol shop, buy krishna idol online india, krishna lotus throne statue luxury, griha pravesh gift ideas",
    purpose: "Love, Joy, Devotion, Home Mandir, Gift for Wedding",
    features: [
      "White Marble Statue",
      "Height: 37.5 cm (14.8 inch)",
      "Width: 26.5 cm (10.5 inch)",
      "Depth: 18.5 cm (7.25 inch)",
      "Weight: 13.11 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "shri-krishna-marble",
    name: "Shri Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 47250,
    originalPrice: 47250,
    material: "Marble Statue",
    height: "15 inches",
    weight: "3.70 kg",
    description: "Embrace divine love with a 15-inch white marble Krishna statue. Premium Jaipur craftsmanship for your home. Enjoy free worldwide delivery.",
    longDescription: "A glorious 15-inch (38 cm) white marble statue of Shri Krishna playing his divine flute. Expertly carved and adorned with beautiful painted details and delicate stones, this enchanting murti perfectly captures the supreme love, joy, and magnetism of the Lord.",
    images: [
      "/products/shri-krishna-hero.png",
      "/products/shri-krishna-1.png"
    ],
    rating: 5.0,
    reviews: 3,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Hand-painted White Marble with Stones",
    origin: "MADE IN INDIA",
    keywords: "shri krishna murti price, krishna marble idol jaipur, buy krishna murti online india, white marble krishna statue shop, affordable luxury krishna idol, home inauguration gift",
    purpose: "Devotion, Love, Home Mandir, Puja Room, Auspicious Gift",
    features: [
      "White Marble Statue",
      "Height: 38 cm (15 inch)",
      "Width: 7.5 cm (3 inch)",
      "Depth: 20.5 cm (8 inch)",
      "Weight: 3.70 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },

  {
    id: "hanuman-sanjeevani",
    name: "Hanuman Ji Carrying Mount Dron of Sanjeevani Herbs",
    deity: "Hanuman — The Supreme Devotee",
    price: 95865,
    originalPrice: 95865,
    material: "White Marble",
    height: "19.5 inches",
    weight: "10 kg",
    description: "Bring home this 19.5-inch white marble Hanuman murti. Handcrafted in Jaipur with divine precision. Order today for free worldwide shipping.",
    longDescription: "A glorious 19.5-inch (49.5 cm) white marble statue depicting Lord Hanuman flying with Mount Dron to bring the life-saving Sanjeevani herbs. Handcrafted with exquisite detailing, painted with vibrant colors, and adorned with delicate stones, this murti perfectly captures the strength, devotion, and urgency of the Supreme Devotee.",
    images: [
      "/products/hanuman-sanjeevani-hero.png",
      "/products/hanuman-sanjeevani-1.png"
    ],
    rating: 4.0,
    reviews: 1,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted White Marble with Stones",
    origin: "MADE IN INDIA",
    keywords: "hanuman murti price, hanuman sanjeevani statue jaipur, lord hanuman idol shop, buy hanuman statue online india, marble hanuman statue jaipur premium, house protection deity",
    purpose: "Protection, Health, Devotion, Home Mandir, Temple, Devotional Gift",
    features: [
      "White Marble Statue",
      "Height: 49.5 cm (19.5 inch)",
      "Width: 23 cm (9 inch)",
      "Depth: 7.5 cm (3 inch)",
      "Weight: 10 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "vishnu-chaturbhuja",
    name: "Chaturbhuja Vishnu",
    deity: "Vishnu — The Preserver",
    price: 85365,
    originalPrice: 85365,
    material: "White Marble",
    height: "14.7 inches",
    weight: "3.50 kg",
    description: "Bring home this 14.7-inch white marble Vishnu Chaturbhuja. Intricately hand-carved by Jaipur masters. Secure yours with free shipping.",
    longDescription: "A magnificent 14.7-inch (37.5 cm) white marble statue of Lord Vishnu in his four-armed (Chaturbhuja) form, holding the conch, discus, mace, and lotus. This divine murti is adorned with exquisite detailing and represents the supreme preserver of the universe.",
    images: [
      "/products/vishnu-chaturbhuja-hero.png",
      "/products/vishnu-chaturbhuja-1.png",
      "/products/vishnu-chaturbhuja-2.png"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-painted White Marble with Gold Details",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 37.5 cm (14.7 inch)",
      "Width: 7.5 cm (3 inch)",
      "Depth: 17 cm (6.7 inch)",
      "Weight: 3.50 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "krishna-omnibenevolent",
    name: "The Omnibenevolent Gaze of Lord Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 73920,
    originalPrice: 73920,
    material: "White Marble",
    height: "24 inches",
    weight: "28.20 kg",
    description: "Experience divine grace with a 24-inch white marble Krishna murti. An authentic handcrafted Jaipur treasure. Order with free shipping.",
    longDescription: "A breathtaking 24-inch (61 cm) white marble statue of Lord Krishna playing his divine flute. Known as 'The Omnibenevolent Gaze', this masterpiece is adorned with intricate golden painting, sparkling jewels, and a majestic crown. The statue weighs 28.20 kg, making it a substantial and deeply commanding centerpiece for any spiritual space.",
    images: [
      "/products/krishna-omnibenevolent-hero.jpg",
      "/products/krishna-omnibenevolent-1.jpg",
      "/products/krishna-omnibenevolent-2.jpg",
      "/products/krishna-omnibenevolent-3.jpg",
      "/products/krishna-omnibenevolent-4.jpg"
    ],
    rating: 5.0,
    reviews: 1,
    inStock: true,
    badge: "Masterpiece",
    category: "Marble",
    finish: "Hand-painted White Marble with Jewels",
    origin: "MADE IN INDIA",
    features: [
      "White Marble Statue",
      "Height: 61 cm (24 inch)",
      "Width: 30.5 cm (12 inch)",
      "Depth: 12.5 cm (5 inch)",
      "Weight: 28.20 kg",
      "100% Handmade in India",
      "Fully Insured Order",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "shivalingam-black-small",
    name: "6\" Small Black Marble Shivalingam",
    deity: "Shiva — The Infinite Consciousness",
    price: 6600,
    originalPrice: 6600,
    material: "Black Marble",
    height: "6 inches",
    weight: "Handmade",
    description: "Enhance your pooja with a 6-inch black marble Shivalingam. Sacred, handcrafted quality from Jaipur. Bring divine energy home today.",
    longDescription: "A perfectly proportioned 6\" Small Black Marble Shivalingam, handcrafted from pure black stone. This sacred murti represents Lord Shiva in his most abstract and infinite form, ideal for daily puja and home mandir installation.",
    images: ["/products/shiva-lingam-hero.jpg", "/products/shiva-lingam-black.jpg"],
    rating: 5.0,
    reviews: 8,
    inStock: true,
    badge: "Just Added",
    category: "Marble",
    finish: "Smooth Black Polish with Hand-painted Tripundra",
    origin: "MADE IN INDIA",
    features: [
      "6\" Small Black Marble Shivalingam",
      "Handmade Sacred Puja Idol",
      "Fully Insured Order",
      "100% Handmade in India",
      "Easy Returns within 7 days"
    ],
  },
  {
    id: "ganesha-dancing-large",
    name: "36\" Large Dancing Ganesha",
    deity: "Ganesha — Remover of Obstacles",
    price: 420000,
    originalPrice: 420000,
    material: "White Marble",
    height: "36 inches",
    weight: "Handmade",
    description: "Celebrate new beginnings with a 36-inch white marble dancing Ganesha. A premium Jaipur handcrafted masterpiece. Shop with free shipping.",
    longDescription: "Exquisite 36\" Large Dancing Ganesha handmade from pure White Marble. A mesmerizing Ganpati Statue capturing the joyful dance of the Lord of New Beginnings.",
    images: [
      "/products/dancing-ganesha-hero.jpg",
      "/products/dancing-ganesha-1.jpg",
      "/products/dancing-ganesha-3.jpg"
    ],
    rating: 5.0,
    reviews: 12,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-polished White with Gold Accents",
    origin: "MADE IN INDIA",
    features: [
      "36\" Large Dancing Ganesha",
      "Handmade White Marble Ganpati Statue",
      "Fully Insured Order",
      "100% Handmade in India",
      "Easy Returns within 7 days"
    ],
  },

  {
    id: "durga-marble-01",
    name: "Maa Durga",
    deity: "Durga — The Invincible Goddess",
    price: 22500,
    originalPrice: 28000,
    material: "White Marble",
    height: "18 inches",
    weight: "4.8 kg",
    description: "Welcome Goddess Durga with an 18-inch white marble murti. Hand-carved with devotion by Jaipur artisans. Enjoy free international shipping.",
    longDescription: "This extraordinary Durga Mata murti is carved from the finest White marble by a family of sculptors whose lineage served the Rajput royal courts of Jaipur for seven generations. The Goddess is shown in her Mahishasuramardini form — triumphant, seated gracefully on her sacred lion (Simha), eight arms each holding a divine weapon: trishul, sword, bow, chakra, lotus, and bestowing both abhaya (fearlessness) and varada (boon-giving) blessings. The detailed folds of her garments and each strand of her crown's pearl strings are carved with microscopic precision. The pure white marble symbolizes the Goddess's transcendent purity and victory over darkness.",
    images: ["/products/durga-marble.jpg"],
    rating: 4.9,
    reviews: 187,
    inStock: true,
    badge: "New Arrival",
    category: "Marble",
    finish: "Hand-polished White Marble",
    origin: "Jaipur, Rajasthan",
    features: [
      "Pure White marble",
      "Royal court sculptor lineage",
      "Mahishasuramardini iconography",
      "Temple-consecrated",
      "Climate-controlled shipping crate",
    ],
  },
  {
    id: "krishna-brass-01",
    name: "Shri Krishna",
    deity: "Krishna — The Divine Flutist",
    price: 16500,
    originalPrice: 21000,
    material: "Panchaloha Brass",
    height: "16 inches",
    weight: "3.6 kg",
    description: "Shop this 16-inch Panchaloha brass Krishna statue. Authentic traditional casting from Tamil Nadu. Elevate your mandir with free shipping.",
    longDescription: "This magnificent Krishna murti captures the Lord in his most beloved Venugopal (flute-playing) form — standing in the graceful Tribhanga posture, with his flute (bansuri) held to his lips, peacock feather crown, and the eternally divine smile that melts all hearts. Cast in Panchaloha brass using the lost-wax method perfected in Swamimalai over 2,000 years, the deep golden-bronze patina develops richer character with each passing year. The intricate surface detailing — from the individual feathers of his crown to the fine beadwork of his necklaces — took the master artisan over six weeks to complete by hand. Traditionally adorned with fresh jasmine and rose garlands during worship.",
    images: ["/products/krishna-brass.jpg"],
    rating: 4.8,
    reviews: 241,
    inStock: true,
    badge: "Customer Favourite",
    category: "Bronze",
    finish: "Antique Brass Patina",
    origin: "Swamimalai, Tamil Nadu",
    features: [
      "Panchaloha (5-metal alloy)",
      "Lost-wax Swamimalai casting",
      "Tribhanga Venugopal form",
      "Deepens with age beautifully",
      "Includes garland-ready hook",
    ],
  },

  {
    id: "shiva-crystal-01",
    name: "Shiva Lingam",
    deity: "Shiva — The Infinite Consciousness",
    price: 8999,
    originalPrice: 11500,
    material: "Narmada Sphatik Crystal",
    height: "6 inches",
    weight: "1.2 kg",
    description: "Radiate purity with a 6-inch Narmada sphatik crystal Shiva. Sacred, authentic spiritual energy. Invite the divine with free shipping.",
    longDescription: "These sacred Sphatik Shiva Lingams are naturally formed in the Narmada River — one of India's holiest rivers. Each lingam is unique in its veining and translucency, shaped by millions of years of riverbed polishing. Sphatik (rock crystal quartz) is considered the purest manifestation of Lord Shiva's cosmic energy in the Shaiva tradition. The crystal's natural piezoelectric properties are believed to amplify meditation and prayer. Comes with a handcrafted brass yoni base, engraved with sacred geometric patterns.",
    images: ["/products/shiva-crystal.jpg"],
    rating: 4.9,
    reviews: 312,
    inStock: true,
    category: "Crystal",
    finish: "Natural Polished",
    origin: "Narmada River, Madhya Pradesh",
    features: [
      "100% natural Narmada crystal",
      "Unique formation per piece",
      "Brass yoni base included",
      "Comes with abhishek kit",
      "Vedic certification",
    ],
  },
  {
    id: "hanuman-pancha-01",
    name: "Panchamukhi Hanuman",
    deity: "Hanuman — The Devotee Supreme",
    price: 15750,
    originalPrice: 19000,
    material: "Panchaloha Bronze",
    height: "14 inches",
    weight: "3.1 kg",
    description: "Secure a 14-inch Panchaloha bronze Hanuman murti. Premium traditional craftsmanship from Tamil Nadu. Order today for free global shipping.",
    longDescription: "The Panchamukhi (five-faced) form of Hanuman is exceptionally rare in murti-making, as each face must be perfectly proportioned while maintaining devotional accuracy. The five faces — Hanuman (north), Narasimha (south), Garuda (west), Varaha (east), and Hayagriva (sky-facing) — represent mastery over all five directions and protection from all negative forces. This murti is cast by a fourth-generation master craftsman from Kumbakonam, Tamil Nadu, following strict Agama Shastra specifications. It is especially revered for installation at home entrances as a powerful protective deity.",
    images: ["/products/hanuman-bronze.jpg"],
    rating: 4.8,
    reviews: 203,
    inStock: false,
    badge: "Sold Out",
    category: "Bronze",
    finish: "Antique Bronze",
    origin: "Kumbakonam, Tamil Nadu",
    features: [
      "Panchamukhi (5-faced) form",
      "Agama Shastra compliant",
      "Protective home deity",
      "Consecrated with Vedic rituals",
      "Comes with puja guide",
    ],
  },
];

export const categories = ["All", "Bronze", "Marble", "Crystal", "Brass", "Wood"];

export const testimonials = [
  {
    name: "Priya Sharma",
    location: "Mumbai",
    text: "The Ganesha murti I received is breathtaking. The craftsmanship is extraordinary — I can see every individual detail. It now sits as the centerpiece of our home mandir.",
    rating: 5,
    avatar: "PS",
  },
  {
    name: "Rajesh Iyer",
    location: "Chennai",
    text: "As someone who has collected temple art for 20 years, I can say the quality here is museum-grade. The Lakshmi murti exceeded every expectation. The dark patina is divine.",
    rating: 5,
    avatar: "RI",
  },
  {
    name: "Dr. Anita Kulkarni",
    location: "Pune",
    text: "Ordered the Durga Mata for our puja room. The packaging was as luxurious as the murti itself. The marble is flawlessly pure. She was moved to tears — it's truly divine.",
    rating: 5,
    avatar: "AK",
  },
  {
    name: "Vikram Menon",
    location: "Bangalore",
    text: "The Krishna murti is the most beautiful thing in our home. The brass patina glows during evening aarti. Authenticity certificate gave complete confidence. Highly recommended.",
    rating: 5,
    avatar: "VM",
  },
];
